name: WordPress Coding Standards

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    strategy:
      matrix:
        php: [ 8.2 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer run-script packages-install

      - name: Run PHP Code Sniffer
        run: composer run-script lint:php
